### ISSUE TITLE
Harmony and LiteDB

### ISSUE THREAD

**Issue by Reyah9999** [RowpannSCP/XP#4]
When I try to install the plugin it requires Harmony and LiteDB, provide links to these applications.

**Comment by moddedmcplayer** [comment]
https://github.com/pardeike/Harmony/releases/download/v2.2.2.0/Harmony.2.2.2.0.zip (4.7.2/4.8 if one dosent work choose the other)
Harmony is included with exiled by default. If you have an install you can simply use that one.
LiteDb should be in the first initial release, they don't seem to provide prebuilt binaries on their GitHub.

**Comment by moddedmcplayer** [comment]
https://github.com/pardeike/Harmony/releases/download/v2.2.2.0/Harmony.2.2.2.0.zip (4.7.2/4.8 if one dosent work choose the other)
Harmony is included with exiled by default. If you have an install you can simply use that one.
LiteDb should be in the first initial release, they don't seem to provide prebuilt binaries on their GitHub.
