### ISSUE TITLE
Reset everyone command

### ISSUE THREAD

**Issue by Miggas** [RowpannSCP/XP#6]
There's no command or simple way to reset everyone's level to 0, can that be added?

**Comment by Miggas** [comment]
And also, would it be hard to implement a stop/pause command for when iI'm running events on my server people don't get any progress?

**Comment by moddedmcplayer** [comment]
> There's no command or simple way to reset everyone's level to 0, can that be added?

Delete the database file

**Comment by moddedmcplayer** [comment]
> And also, would it be hard to implement a stop/pause command for when iI'm running events on my server people don't get any progress?

Do you think disabling the plugin is enough or do you want me to add a command?

**Comment by Miggas** [comment]
> > There's no command or simple way to reset everyone's level to 0, can that be added?
> 
> Delete the database file

Deleting the database file requires stopping the server, is adding a command that send a query to delete and recreate de table to hard?


> > And also, would it be hard to implement a stop/pause command for when I'm running events on my server people don't get any progress?
> 
> Do you think disabling the plugin is enough or do you want me to add a command?

Disabling the plugin requires rebooting the server or at least reloading plugin configs but my server has a lot of plugins, and a reload usually breaks something requiring a reboot, a command to enable and disable the plugin would be nice or at least to pause during the current round, going back to normal the next round.

I used to program in C# to many years ago, and doing this by myself would take a long time, but if you don't want to add this functionality I'll try and add it myself, and one more thing, are you by any chance planning to change the database to mongoDB in the future?

**Comment by moddedmcplayer** [comment]
> > > There's no command or simple way to reset everyone's level to 0, can that be added?
> > 
> > Delete the database file
> 
> Deleting the database file requires stopping the server, is adding a command that send a query to delete and recreate the table too hard?
> 
> 
> > > And also, would it be hard to implement a stop/pause command for when I'm running events on my server people don't get any progress?
> > 
> > Do you think disabling the plugin is enough or do you want me to add a command?
> 
> Disabling the plugin requires rebooting the server or at least reloading plugin configs but my server has a lot of plugins, and a reload usually breaks something requiring a reboot, a command to enable and disable the plugin would be nice or at least to pause during the current round, going back to normal the next round.
> 
> I used to program in C# to many years ago, and doing this by myself would take a long time, but if you don't want to add this functionality I'll try and add it myself, and one more thing, are you by any chance planning to change the database to mongoDB in the future?

Let me contact you in discord
