### ISSUE TITLE
Harmony Patch issue (Exiled 8.2.1)

### ISSUE THREAD

**Issue by tooobiiii** [RowpannSCP/XP#7]
i have found out that the Plugin throws an error after i updated to Exiled v8.2.1. 
![image](https://github.com/RowpannSCP/XP/assets/132146628/65fce1b8-fda4-41d1-acde-b143d914315a)

^ Error occurs

They changed something that breaks the patching i suppose you will have to look into it

Tobi

**Comment by moddedmcplayer** [comment]
why close smh

**Comment by moddedmcplayer** [comment]
Oh, this isnt even my plugin causing it, I dont patch that method
